### ISSUE TITLE
登入供货商，Seller dashboard页面，layout broken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#102]
![image](https://user-images.githubusercontent.com/44828242/48593456-de0c3980-e987-11e8-9650-654e77272873.png)

**Comment by ErisFU** [comment]
![5](https://user-images.githubusercontent.com/41175757/49559088-69099f80-f948-11e8-81de-ce78cab4d167.png)
OK donedone登入供货商，Seller dashboard页面，layout broken #102
