### ISSUE TITLE
采购商

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#105]
![image](https://user-images.githubusercontent.com/41175158/48594051-3ba18580-e98a-11e8-9e5d-c206c5e0752a.png)
http://www.membersheep.cn/MyPage/Order

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48594106-71466e80-e98a-11e8-99ab-508ecfadf128.png)
http://www.membersheep.cn/MyPage/Order

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48594146-9a66ff00-e98a-11e8-8436-427fa14b4f8f.png)
http://www.membersheep.cn/MyPage/Order

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48594263-edd94d00-e98a-11e8-9b3a-4672ad4da6ee.png)

![image](https://user-images.githubusercontent.com/41175158/48594248-ddc16d80-e98a-11e8-96af-3ee38afec193.png)
http://www.membersheep.cn/MyPage/Order

**Comment by Jvisions** [comment]
这个延后
