### ISSUE TITLE
登入供货商，sales management页面问题（layout broken ）

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#109]
![image](https://user-images.githubusercontent.com/44828242/48594722-c5eae900-e98c-11e8-8f7a-c551ca28c6a2.png)

**Comment by ErisFU** [comment]
![6](https://user-images.githubusercontent.com/41175757/49559256-26949280-f949-11e8-96ad-382fda129ecd.png)
OK 登入供货商，sales management页面问题（layout broken ） #109
