### ISSUE TITLE
除了首页页面，搜索框出现一个空白

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#110]
![image](https://user-images.githubusercontent.com/41175158/48594769-f894e180-e98c-11e8-8650-b1c5c969e33e.png)

**Comment by ErisFU** [comment]
![wx20181116-112933](https://user-images.githubusercontent.com/41175757/48596199-ed44b480-e992-11e8-8133-7973500b0d8b.png)
ok  done 之前中英文长度导致的，现在定位好了
