### ISSUE TITLE
Team profile 需要更新

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#116]
![image](https://user-images.githubusercontent.com/44828242/48600114-8da3d480-e9a5-11e8-92cc-31441d93c8d9.png)

网址：http://www.membersheep.cn/aboutus

**Comment by ErisFU** [comment]
![7](https://user-images.githubusercontent.com/41175757/49560048-ec78c000-f94b-11e8-802d-179374a2f2ab.png)Team profile 需要更新 #116
