### ISSUE TITLE
Order Details 提示框没显示尺寸信息

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#136]
![image](https://user-images.githubusercontent.com/44828242/48682855-4c9a0300-ebe5-11e8-8bf9-6e9116e6501d.png)

**Comment by Jvisions** [comment]
数据问题，没有尺寸信息

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48696117-f7c5af00-ec1b-11e8-897b-72b17c35de05.png)
