### ISSUE TITLE
动作统一，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#14]
![image](https://user-images.githubusercontent.com/44828242/48189464-3e451f00-e37b-11e8-9d2e-0151cf42c5f3.png)

**Comment by Jvisions** [comment]
@piaoseeun 这个抄给蕊改

**Comment by piaoseeun** [comment]
@Jvisions ok

**Comment by ErisFU** [comment]
done OK
