### ISSUE TITLE
网速慢的时候，多次点击“Add to shopping Cart ”按钮（测试：18次）点击Settlement ->点击浏览器的后退->点击进去商品页面->出现购物车异常问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#143]
![image](https://user-images.githubusercontent.com/44828242/48683148-af3fce80-ebe6-11e8-8620-0d5828d0e152.png)

**Comment by longpizi** [comment]
马上改版，响应式页面，下一版不会出现这种问题
