### ISSUE TITLE
通过Pre-order，订单完成后，还是留在Pre-order目录

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#144]
![image](https://user-images.githubusercontent.com/44828242/48683218-08a7fd80-ebe7-11e8-870b-f7f66ce1e134.png)

**Comment by Jvisions** [comment]
这个我没看懂啊

**Comment by Jvisions** [comment]
这个不算bug，预购单可以自己删除
