### ISSUE TITLE
采购商个人中心my account->favorite->all products

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#146]
![image](https://user-images.githubusercontent.com/41175158/48684578-4ad43d80-ebed-11e8-82a2-b90aa55295e2.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49560775-bc7eec00-f94e-11e8-9c32-cc2407123223.png)
采购商个人中心my account->favorite->all products #146
