### ISSUE TITLE
点击新品按钮进入页面

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#149]
![image](https://user-images.githubusercontent.com/41175158/48685211-12822e80-ebf0-11e8-95bc-227b7843e4e4.png)

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49563512-27cebb00-f95b-11e8-9a79-adc367f8d33e.png)
O k已经加宽 点击新品按钮进入页面 #149
