### ISSUE TITLE
无法修改，保存

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#151]
![image](https://user-images.githubusercontent.com/44828242/48685476-79541780-ebf1-11e8-9136-301cd7a3276d.png)

**Comment by Jvisions** [comment]
要先点击modify才能修改
![image](https://user-images.githubusercontent.com/39116593/48694207-b252b300-ec16-11e8-9473-aa78f77c03a7.png)
