### ISSUE TITLE
information 页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#154]
![image](https://user-images.githubusercontent.com/44828242/48685611-1dd65980-ebf2-11e8-825d-6e0e18721235.png)

**Comment by Jvisions** [comment]
这个是什么问题？我没看懂，我测试官网咨询没有问题啊
![1542614133 1](https://user-images.githubusercontent.com/39116593/48693205-a9141700-ec13-11e8-8858-40a4f69b0756.jpg)

**Comment by Jvisions** [comment]
这个111是我新加的啊
