### ISSUE TITLE
发布商品页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#161]
![image](https://user-images.githubusercontent.com/44828242/48687543-da351d00-ebfc-11e8-8c6e-31fb7b281410.png)

![image](https://user-images.githubusercontent.com/44828242/48687631-35670f80-ebfd-11e8-9d34-b2cdb7a78c72.png)

**Comment by Jvisions** [comment]
上面的那个要重新设计插件，而且改动比较大比较多，我测试图片是显示没有问题的
