### ISSUE TITLE
销售额管理页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#163]
![image](https://user-images.githubusercontent.com/44828242/48687692-765f2400-ebfd-11e8-894e-5c0b3b4534f5.png)

网址：http://www.membersheep.cn/AdminSeller/SellingPrice

**Comment by Jvisions** [comment]
这个没看懂，就是按照提现申请日期来排序的啊

**Comment by piaoseeun** [comment]
这个我也不太清楚，等等我问下
