### ISSUE TITLE
供货商登入，点击商品数量（+），出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#165]
![image](https://user-images.githubusercontent.com/44828242/48691819-e88c3480-ec0e-11e8-8b5e-cb81eb7f7a2d.png)
![image](https://user-images.githubusercontent.com/44828242/48691863-13768880-ec0f-11e8-8bb2-4e0465c27c47.png)

网址：http://www.membersheep.cn/Goods/Index?goodsId=7605

**Comment by Jvisions** [comment]
这是你用供货商的账号去买东西是不行的，供货商是卖东西的，采购商是买东西的，至于确定和取消这两个中文是浏览器自带的alert方法中的改不了，国家所在地不一样就显示不一样的文字
