### ISSUE TITLE
bestseller 热销商品页面

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#167]
![image](https://user-images.githubusercontent.com/41175158/48746817-f80d8b00-ecab-11e8-8147-976e175bdb61.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48747634-d7930000-ecae-11e8-8454-23d4f5cca887.png)
这三个页面都是这样

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49563544-4f258800-f95b-11e8-86d0-852d1833c36b.png)
OK bestseller 热销商品页面 #167
 Open
