### ISSUE TITLE
新品页面 热销商品 推荐页面

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#168]
![image](https://user-images.githubusercontent.com/41175158/48747881-f2b23f80-ecaf-11e8-8b11-69738d0dfb36.png)

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49563586-70867400-f95b-11e8-8100-944fa4c816be.png)
OK 新品页面 热销商品 推荐页面 #168
