### ISSUE TITLE
卖家excel文件页面，英文字打错了

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#169]
![image](https://user-images.githubusercontent.com/44828242/48747918-08276980-ecb0-11e8-95c4-fda0f4ed09ef.png)

![image](https://user-images.githubusercontent.com/44828242/48747872-eb8b3180-ecaf-11e8-9c5c-68e1152ac725.png)

![image](https://user-images.githubusercontent.com/44828242/48748058-7bc97680-ecb0-11e8-9696-1947709f64e2.png)

网址：http://www.membersheep.cn/AdminSeller/GetGoodsFileUpLoadExcel

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49564801-d674fa80-f95f-11e8-9d80-fb6a4a4873d0.png)
![3](https://user-images.githubusercontent.com/41175757/49564803-d8d75480-f95f-11e8-8ad9-be4f1487b27c.png)
![1](https://user-images.githubusercontent.com/41175757/49564809-db39ae80-f95f-11e8-8a75-3d2ab6055cf3.png)
ok 卖家excel文件页面，英文字打错了 #169
