### ISSUE TITLE
卖家发布商品页面，出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#172]
![image](https://user-images.githubusercontent.com/44828242/48749020-ef20b780-ecb3-11e8-8426-2321acdfe920.png)
![image](https://user-images.githubusercontent.com/44828242/48749121-6ce4c300-ecb4-11e8-9665-f6a956011622.png)

![image](https://user-images.githubusercontent.com/44828242/48749077-38710700-ecb4-11e8-98ff-422f133b90cd.png)

![image](https://user-images.githubusercontent.com/44828242/48749087-4161d880-ecb4-11e8-8aed-8cb2618564a2.png)

![image](https://user-images.githubusercontent.com/44828242/48749097-49217d00-ecb4-11e8-8b7a-14b2ab8a9b44.png)

网址：http://www.membersheep.cn/AdminSeller/GoodsRegistration

**Comment by Jvisions** [comment]
插件内部方法，无法做到国际化，后面在换插件吧
