### ISSUE TITLE
发布商品页面，small choice都是中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#173]
![image](https://user-images.githubusercontent.com/44828242/48755609-e4285000-ecd0-11e8-8f75-f8420face84c.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48756467-42a2fd80-ecd4-11e8-8e42-63a6b314efc4.png)
我看的都是英文的啊
