### ISSUE TITLE
上传商品图片，出现中文字

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#174]
![image](https://user-images.githubusercontent.com/44828242/48755834-ba235d80-ecd1-11e8-822b-0d624e4a5a93.png)

**Comment by piaoseeun** [comment]
![image](https://user-images.githubusercontent.com/44828242/48759446-0bd1e500-ecde-11e8-92a1-9967f159350f.png)
金成我这边还是这样，还没上传好了吗？

**Comment by Jvisions** [comment]
经理还没上传
