### ISSUE TITLE
首页点击品牌按钮

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#176]
![image](https://user-images.githubusercontent.com/41175158/48756268-6dd91d00-ecd3-11e8-8d61-b688618a8453.png)

**Comment by longpizi** [comment]
![bug](https://user-images.githubusercontent.com/37363309/48823375-96c4e500-ed9b-11e8-9883-54c946cee50b.png)
下一版ok
