### ISSUE TITLE
offer product 页面 layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#177]
![image](https://user-images.githubusercontent.com/44828242/48756517-71b96f00-ecd4-11e8-837d-43a92584d54e.png)
![image](https://user-images.githubusercontent.com/44828242/48756559-96154b80-ecd4-11e8-9493-e67918278ed1.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49564333-1b982d00-f95e-11e8-8c4c-660d5b48a922.png)
OK
