### ISSUE TITLE
message页面，请对齐

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#180]
![image](https://user-images.githubusercontent.com/44828242/48814934-a29eb000-ed77-11e8-9972-dd1bba30cb90.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49564549-e2ac8800-f95e-11e8-81f7-1c0bbe52f47b.png)
OK message页面，请对齐 #180
