### ISSUE TITLE
新品页面 http://www.membersheep.cn/Home/NewGoods

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#184]
![image](https://user-images.githubusercontent.com/41175158/48822407-f9b47d00-ed97-11e8-9ce5-ee7654825560.png)

**Comment by Amber-Lily** [comment]
还有美元的标志也要调整一下

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49564888-379cce00-f960-11e8-9977-87711d63bd12.png)
ok 新品页面 http://www.membersheep.cn/Home/NewGoods #184
