### ISSUE TITLE
英文意思不对了

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#186]
![image](https://user-images.githubusercontent.com/44828242/48825258-d1ca1700-eda1-11e8-9768-9592b49b3ad2.png)

![image](https://user-images.githubusercontent.com/44828242/48825246-c7a81880-eda1-11e8-9f5a-6db31707a730.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48978347-4f18c300-f0e5-11e8-9489-7ee33295cc59.png)
我这里显示是search啊，没问题
