### ISSUE TITLE
发布品牌，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#197]
![image](https://user-images.githubusercontent.com/44828242/48829792-1fe51780-edae-11e8-8fde-230cfe618ab8.png)

![image](https://user-images.githubusercontent.com/44828242/48829687-db597c00-edad-11e8-8ded-5a06448767a1.png)

**Comment by Jvisions** [comment]
和小龙商量还是不改了，随便供货商分配，每个人的分配方法不一样么
