### ISSUE TITLE
采购商 qwerty123@naver.com

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#199]
![image](https://user-images.githubusercontent.com/41175158/48831066-085b5e00-edb1-11e8-96b8-2094081fb411.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49569408-d29ca480-f96e-11e8-8747-415480e23778.png)
![2](https://user-images.githubusercontent.com/41175757/49569412-d4666800-f96e-11e8-8c50-82c1b602a202.png)

**Comment by ErisFU** [comment]
ok 采购商 qwerty123@naver.com #199
