### ISSUE TITLE
采购商购物车页面出现不明竖线，http://www.membersheep.cn/Cart/Index

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#202]
![image](https://user-images.githubusercontent.com/41175158/48876618-e8bc4800-ee39-11e8-8344-7ee8e08907b5.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49571740-0d094000-f975-11e8-81cc-0fbece137ade.png)
OK 
采购商购物车页面出现不明竖线，
