### ISSUE TITLE
main->preorder->order information 按钮,  供货商能进去采购商页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#205]
![image](https://user-images.githubusercontent.com/44828242/48877917-579c9f80-ee40-11e8-9584-b806a79e86ae.png)
![image](https://user-images.githubusercontent.com/44828242/48877966-7ac74f00-ee40-11e8-99bc-5ce4a6959f49.png)
![image](https://user-images.githubusercontent.com/44828242/48877964-7a2eb880-ee40-11e8-9b28-a45a856516a9.png)

**Comment by Jvisions** [comment]
这个后面统一再改
