### ISSUE TITLE
首页框选处有缝隙，其他页面多出了一截

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#21]
![image](https://user-images.githubusercontent.com/41175158/48238409-e69fc580-e405-11e8-9731-82f4d032a952.png)
![image](https://user-images.githubusercontent.com/41175158/48238420-f28b8780-e405-11e8-9a37-08332f7117c7.png)
![image](https://user-images.githubusercontent.com/41175158/48238433-fa4b2c00-e405-11e8-93a0-b0e309bfad16.png)

**Comment by Jvisions** [comment]
这个抄给蕊改，蕊在改首页 @Amber-Lily
