### ISSUE TITLE
首字大写

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#211]
![image](https://user-images.githubusercontent.com/44828242/48883458-e1596680-ee5a-11e8-8aaa-c7af23ee59b7.png)

网址：http://www.membersheep.cn/Help/Faq

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49572101-00391c00-f976-11e8-8f19-3fc7483f2c37.png)
首字大写 #211
