### ISSUE TITLE
供货商登入，Brandnawa所有商品页面菜单，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#214]
![image](https://user-images.githubusercontent.com/44828242/48884593-1c11cd80-ee60-11e8-8413-6974bf8e0643.png)
http://www.membersheep.cn/Store/Index?sellerId=112

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49572499-eb10bd00-f976-11e8-9006-338fdb211e30.png)
供货商登入，Brandnawa所有商品页面菜单，layout broken #214
