### ISSUE TITLE
采购商点击detail，对齐的方式不同http://www.membersheep.cn/MyPage/Order

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#215]
![image](https://user-images.githubusercontent.com/41175158/48884857-22ed1000-ee61-11e8-923d-fa5b82aa3fa6.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49575365-78efa680-f97d-11e8-9255-5de4bc22f293.png)
采购商点击detail，对齐的方式不同
