### ISSUE TITLE
供货商登入，能进去采购商页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#216]
![image](https://user-images.githubusercontent.com/44828242/48884901-4617bf80-ee61-11e8-9db6-3fee26141fc6.png)
![image](https://user-images.githubusercontent.com/44828242/48884908-4adc7380-ee61-11e8-8ac7-f3e20a2e17ef.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by Jvisions** [comment]
这个涉及到逻辑问题，改动会比较大，延后
