### ISSUE TITLE
供货商需要收藏页面？（供货商登入，能进去采购商页面）

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#218]
![image](https://user-images.githubusercontent.com/44828242/48885020-bb839000-ee61-11e8-908f-2f436091f027.png)
![image](https://user-images.githubusercontent.com/44828242/48885026-c3433480-ee61-11e8-82a9-a4d5bfdfead0.png)
http://www.membersheep.cn/MyPage/Bookmark
我觉得供货商登入页面"favorite"按钮也不用了，金成帮我看一下，谢谢

**Comment by Jvisions** [comment]
这种供货商进采购商的暂时不做处理，后面统一在做

**Comment by piaoseeun** [comment]
OK
