### ISSUE TITLE
供货商mycenter页面出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#221]
![image](https://user-images.githubusercontent.com/44828242/48885302-cbe83a80-ee62-11e8-9ca4-1c3bdefeeb0d.png)

http://www.membersheep.cn/MyPage/MyAddress?per=No%20authority!

**Comment by Jvisions** [comment]
这个暂时不做处理

**Comment by Jvisions** [comment]
中文那个国际化做不了，数据库读的城市很多
