### ISSUE TITLE
首页logo不对齐，其他页面用户名不对齐

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#23]
![image](https://user-images.githubusercontent.com/41175158/48238707-ebb14480-e406-11e8-8a6a-81b41634e911.png)
![image](https://user-images.githubusercontent.com/41175158/48238730-fff54180-e406-11e8-869a-1d6f96420826.png)

**Comment by Jvisions** [comment]
首页的给蕊改吧

**Comment by ErisFU** [comment]
done OK
