### ISSUE TITLE
modify product color 页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#231]
![image](https://user-images.githubusercontent.com/44828242/48885982-2387a580-ee65-11e8-9983-c26f03a6c647.png)
![image](https://user-images.githubusercontent.com/44828242/48886058-795c4d80-ee65-11e8-9f8e-bd17389a2e55.png)
![image](https://user-images.githubusercontent.com/44828242/48886159-c93b1480-ee65-11e8-8033-de9552b0a5c6.png)

http://www.membersheep.cn/AdminSeller/GoodsColoModify?goodsId=7620&goodsPackId=8941

**Comment by longpizi** [comment]
下一版OK
