### ISSUE TITLE
推荐页面，显示一共有四页，但点击下一页基本商品不变http://www.membersheep.cn/Home/NewGoods#top

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#232]
![image](https://user-images.githubusercontent.com/41175158/48886241-30f15f80-ee66-11e8-894e-04a62deeccea.png)
![image](https://user-images.githubusercontent.com/41175158/48886251-3babf480-ee66-11e8-924d-f042c85768d9.png)

**Comment by longpizi** [comment]
下一版OK
