### ISSUE TITLE
推荐页面，按钮布局超出http://www.membersheep.cn/Home/NewGoods

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#237]
![image](https://user-images.githubusercontent.com/41175158/48886807-45cef280-ee68-11e8-8257-590162789b06.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49576365-f9170b80-f97f-11e8-89e9-c40fb210af98.png)
推荐页面，按钮布局超出
