### ISSUE TITLE
首页点击seemore ,点击download没反应，http://www.membersheep.cn/Home/OrandRequestDetails?requestNo=46

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#239]
![image](https://user-images.githubusercontent.com/41175158/48887505-76b02700-ee6a-11e8-872b-475472239501.png)

![image](https://user-images.githubusercontent.com/41175158/48887522-8596d980-ee6a-11e8-98ce-bfcbae510840.png)

**Comment by longpizi** [comment]
下一版OK
