### ISSUE TITLE
OBEY品牌页面搜索品牌名称，结果没有

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#242]
![image](https://user-images.githubusercontent.com/44828242/48887331-e70a7880-ee69-11e8-9835-78f1eb41ebd5.png)

http://www.membersheep.cn/Brand/Index

![image](https://user-images.githubusercontent.com/44828242/48887558-af500080-ee6a-11e8-96f5-8f442d0df491.png)

![image](https://user-images.githubusercontent.com/44828242/48887591-cf7fbf80-ee6a-11e8-9cf8-7e68e1ed95e3.png)

http://www.membersheep.cn/Brand/Index
![image](https://user-images.githubusercontent.com/44828242/48887697-38ffce00-ee6b-11e8-949d-2ee956661ba4.png)

**Comment by Jvisions** [comment]
这个是搜索品牌，不是搜索商品名呢

**Comment by Jvisions** [comment]
这个我没看明白
