### ISSUE TITLE
order request 页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#247]
![image](https://user-images.githubusercontent.com/44828242/48889529-2b4d4700-ee71-11e8-8168-cc0fff23c858.png)
![image](https://user-images.githubusercontent.com/44828242/48889621-6b142e80-ee71-11e8-801e-d31ff7f08c08.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49635279-36d86a80-fa3a-11e8-91f3-538cf1b7ba35.png)
![2](https://user-images.githubusercontent.com/41175757/49635280-38099780-fa3a-11e8-97cc-d381273da395.png)
order request 页面，layout broken #247
