### ISSUE TITLE
店铺全部商品页面，数量与商品不对

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#249]
![image](https://user-images.githubusercontent.com/41175158/48889928-5dab7400-ee72-11e8-9876-5216c3e6c8c5.png)

**Comment by longpizi** [comment]
![image](https://user-images.githubusercontent.com/37363309/49057587-3d493400-f23b-11e8-824b-e2677b77b2ca.png)
