### ISSUE TITLE
显示中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#25]
![image](https://user-images.githubusercontent.com/44828242/48240117-8eb88d00-e40c-11e8-9f1e-05766d266000.png)

**Comment by piaoseeun** [comment]
点击confirm ,/显示中文

**Comment by piaoseeun** [comment]
网址  http://www.membersheep.cn/AdminSeller/Order

**Comment by Jvisions** [comment]
ok
