### ISSUE TITLE
新密码不能和旧密码相同

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#263]
![image](https://user-images.githubusercontent.com/44828242/48925825-23d67e00-ef03-11e8-9ee1-d3472a487403.png)
![image](https://user-images.githubusercontent.com/44828242/48925906-f938f500-ef03-11e8-8871-8bf6cf110b32.png)

**Comment by Jvisions** [comment]
这个还是不改了，让用户自己想怎么改就怎么改吧，做多了限制反而会让人不舒服
