### ISSUE TITLE
calvin klein, calvinklein, ck ->搜索结果都不一样

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#266]
![image](https://user-images.githubusercontent.com/44828242/48927025-b714b100-ef0d-11e8-91b1-6a4694f664d3.png)
http://www.membersheep.cn/Home/Search
![image](https://user-images.githubusercontent.com/44828242/48927046-d4497f80-ef0d-11e8-8568-72e67241daa7.png)
http://www.membersheep.cn/Home/Search
![image](https://user-images.githubusercontent.com/44828242/48927118-939e3600-ef0e-11e8-94e6-c9ae094aaca3.png)
http://www.membersheep.cn/Home/Search

**Comment by Jvisions** [comment]
这个没有问题啊，搜索是模糊查询，从头开始的
