### ISSUE TITLE
BSR ，请去掉一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#271]
![image](https://user-images.githubusercontent.com/44828242/48929820-0adfc400-ef27-11e8-91f6-42d13f8f2d82.png)

http://www.membersheep.cn/Brand/DetailSearch?brandId=362
![image](https://user-images.githubusercontent.com/44828242/48929879-775ac300-ef27-11e8-944f-9945929e329d.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=46
![image](https://user-images.githubusercontent.com/44828242/48929896-99544580-ef27-11e8-824f-aaf89dc52902.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=353
![image](https://user-images.githubusercontent.com/44828242/48929948-0a93f880-ef28-11e8-9731-6747645d9fa4.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=119
![image](https://user-images.githubusercontent.com/44828242/48929965-2eefd500-ef28-11e8-8be1-f7d6e7a96692.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=123
![image](https://user-images.githubusercontent.com/44828242/48930058-c6552800-ef28-11e8-92bc-454dac5bd6fd.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=160
![image](https://user-images.githubusercontent.com/44828242/48930069-dff66f80-ef28-11e8-83cf-7c6e193297c1.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=162
![image](https://user-images.githubusercontent.com/44828242/48930083-f4d30300-ef28-11e8-92df-9bc04f69f480.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=164
![image](https://user-images.githubusercontent.com/44828242/48930112-3499ea80-ef29-11e8-9860-59a80bac2747.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=177

**Comment by Jvisions** [comment]
调成什么？？

**Comment by piaoseeun** [comment]
金成品牌所有页面，都是这样

**Comment by piaoseeun** [comment]
金成品牌所有页面，都是这样
