### ISSUE TITLE
采购商，咨询出现韩文，没有上传图片也显示一张图片，http://www.membersheep.cn/MyPage/MembersheepMessage

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#279]
![image](https://user-images.githubusercontent.com/41175158/48931916-d58da300-ef33-11e8-8b9f-5b8513330163.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48932237-be4fb500-ef35-11e8-9211-b8767c5d1ec6.png)
我是正常的啊，你肯定上传图片了
