### ISSUE TITLE
出现中文，改成英文，http://www.membersheep.cn/MyPage/Order?pageState=

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#284]
![image](https://user-images.githubusercontent.com/41175158/48933371-02918400-ef3b-11e8-84b6-a33f311095e8.png)

![image](https://user-images.githubusercontent.com/41175158/48933362-f7d6ef00-ef3a-11e8-85cb-db8652ca27e6.png)

**Comment by Jvisions** [comment]
这个改动很大，经理说优先级最低
