### ISSUE TITLE
注册页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#295]
![image](https://user-images.githubusercontent.com/44828242/48936194-1f32b980-ef45-11e8-90a8-dcac5834cd1e.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49694090-454f8f00-fbbe-11e8-8a23-23e4f27fe6b6.png)
注册页面，layout broken #295
