### ISSUE TITLE
供货商页面菜单layoutbroken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#301]
![image](https://user-images.githubusercontent.com/44828242/48989861-19b4b980-f167-11e8-9035-167119de6b46.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49694139-fce4a100-fbbe-11e8-98a7-c947d4b24cc9.png)
供货商页面菜单layoutbroken #301
