### ISSUE TITLE
供货商登入，invoice页面出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#309]
![image](https://user-images.githubusercontent.com/44828242/48991052-24258200-f16c-11e8-8bb9-2c4d7840d833.png)

http://www.membersheep.cn/Help/Fapiao

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48996999-437ed800-f189-11e8-994c-30c8fb7cee1b.png)
这个我测试也是英文的
