### ISSUE TITLE
供货商登入，Registered Power Of Attorney/Directory页面，出现韩文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#311]
![image](https://user-images.githubusercontent.com/44828242/48991359-921e7900-f16d-11e8-97ba-40ded873ba33.png)
http://www.membersheep.cn/AdminSeller/AuthorityList

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48996956-0c102b80-f189-11e8-9b46-70639e7e2577.png)
我这里没有问题哎
