### ISSUE TITLE
See Seller All Products页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#313]
![image](https://user-images.githubusercontent.com/44828242/48992523-23441e80-f173-11e8-83bd-4b1f71cc18f7.png)
![image](https://user-images.githubusercontent.com/44828242/48993209-66a08c00-f177-11e8-9fc2-99206d7aab95.png)
www.membersheep.cn/AdminSeller/GoodsColor?goodsId=7620

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/48995181-d61b7900-f181-11e8-9dcc-1738cb439b0d.png)
我这边本地生产测试的没有问题的
