### ISSUE TITLE
Buyer registration process，英文问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#322]
![image](https://user-images.githubusercontent.com/44828242/48998888-e5a1be80-f18f-11e8-8a43-9e7bc3f3a742.png)
http://www.membersheep.cn/Help/BuyerJoin

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49694362-e4c35080-fbc3-11e8-8a43-cc944001b402.png)
Buyer registration process，英文问题 #322
