### ISSUE TITLE
发布尺寸页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#325]
![image](https://user-images.githubusercontent.com/44828242/49005098-d1b28880-f1a0-11e8-9b9d-292dd2feb9ea.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49694843-b8f89880-fbcc-11e8-8c06-3356f37523c3.png)
![2](https://user-images.githubusercontent.com/41175757/49695087-64571c80-fbd0-11e8-9141-6f5db1c5e2b1.png)
发布尺寸页面，layout broken #325
