### ISSUE TITLE
采购商Personal Information页面，按钮

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#326]
![image](https://user-images.githubusercontent.com/44828242/49005877-c6605c80-f1a2-11e8-85f8-134ba160acc2.png)
![image](https://user-images.githubusercontent.com/44828242/49005990-0a536180-f1a3-11e8-897b-6f38c8b31c3e.png)

![image](https://user-images.githubusercontent.com/44828242/49005972-ff003600-f1a2-11e8-84d8-8c54cd2e3fac.png)

**Comment by Jvisions** [comment]
这个就确认吧，上下统一比较好

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49054021-9a3ded80-f22d-11e8-8878-27db29b5f8d1.png)

**Comment by piaoseeun** [comment]
供货商页面，都是modify->save,cancel 这个按钮，选一个统一比较好吧，我先和老板确认一下
