### ISSUE TITLE
忘记密码->查找密码->收到认证邮件->临时密码登不了（采购商）

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#328]
![image](https://user-images.githubusercontent.com/44828242/49053437-16830180-f22b-11e8-932e-a79c3d67c357.png)

![image](https://user-images.githubusercontent.com/44828242/49053409-fa7f6000-f22a-11e8-9b6b-491309ed2502.png)

**Comment by Jvisions** [comment]
我测试可以啊，你把密码复制到文本上看看对不对，可能多了空格什么的
