### ISSUE TITLE
不管英文字母大小写，搜索结果统一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#334]
![image](https://user-images.githubusercontent.com/44828242/49055915-66b29180-f234-11e8-8015-52e13f967063.png)
![image](https://user-images.githubusercontent.com/44828242/49055986-aa0d0000-f234-11e8-818d-963c62bb878e.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49061645-40005500-f24c-11e8-8080-b02ff6c7530e.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49061657-4a225380-f24c-11e8-9d90-ade2fa0f5dcd.png)
我这里查的都是一样的呢

**Comment by piaoseeun** [comment]
金成，我这边再测试也正常的，但是为什么每次测试不一样的结果？？

**Comment by piaoseeun** [comment]
还有你截个图再看看，这些商品不是adidas的

**Comment by Jvisions** [comment]
不会啊，我测试都正常的呀，你是不是点了其他下面的一些按钮了，这些商品是数据问题

**Comment by piaoseeun** [comment]
金成你那边搜索calvin klein这个吧，还是不一样

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49063320-f581d700-f251-11e8-8105-78be9c166f6b.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49063379-26faa280-f252-11e8-880c-8f51c73c94f1.png)
我这里一样的啊
