### ISSUE TITLE
首页，鼠标放在购物车图标，显示“NEW"字

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#335]
![image](https://user-images.githubusercontent.com/44828242/49056470-cd38af00-f236-11e8-9f36-020d82be7547.png)
![image](https://user-images.githubusercontent.com/44828242/49056510-eb9eaa80-f236-11e8-857f-d49f3cb8e2b2.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49139457-d015cb80-f32c-11e8-9ffa-dff0824fcd4f.png)
ok
