### ISSUE TITLE
搜索ADIDAS品牌，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#336]
![image](https://user-images.githubusercontent.com/44828242/49060707-a46de500-f249-11e8-9957-3e6aaec89708.png)
![image](https://user-images.githubusercontent.com/44828242/49060739-c36c7700-f249-11e8-8eba-b292f5c8adc8.png)
![image](https://user-images.githubusercontent.com/44828242/49060776-e9921700-f249-11e8-9c20-c3f29c559717.png)

http://www.membersheep.cn/Home/Search?search=adidas

**Comment by Jvisions** [comment]
商品名称上面有adidas，不是搜索品牌
