### ISSUE TITLE
商品信息显示优先顺序

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#338]
![image](https://user-images.githubusercontent.com/44828242/49061569-fa438c80-f24b-11e8-8793-d425447f6813.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49063705-26aed700-f253-11e8-9879-c56512559aa2.png)
这个页面就是这么设计的，只是个引导页面

**Comment by piaoseeun** [comment]
老板跟我说，需要修改
