### ISSUE TITLE
商品名称不见了

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#340]
![image](https://user-images.githubusercontent.com/44828242/49062248-54dde800-f24e-11e8-9dc0-ffe3586030e6.png)
http://www.membersheep.cn/Home/Search
![image](https://user-images.githubusercontent.com/44828242/49062300-8f478500-f24e-11e8-8345-50ce66769faa.png)

**Comment by Jvisions** [comment]
这个数据库里面就没有商品名
