### ISSUE TITLE
去掉下面页码的边框或者去掉粗黑线，还有页码一栏应在一排，不行就把“Show all pages 20 Article data”删掉http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=209

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#354]
![image](https://user-images.githubusercontent.com/41175158/49123715-a0e36800-f2f4-11e8-9d7b-584b51ac46a0.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49695850-fd3f6500-fbdb-11e8-9d88-a98ec2a86454.png)
去掉下面页码的边框或者去掉粗黑线，还有页码一栏应在一排
![2](https://user-images.githubusercontent.com/41175757/49695896-9a020280-fbdc-11e8-8514-c1dfd5c06f20.png)

**Comment by ErisFU** [comment]
黑线都统一的，不要去掉了
