### ISSUE TITLE
供货商，notice payment the deposit 页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#362]
![image](https://user-images.githubusercontent.com/44828242/49124877-ff124a00-f2f8-11e8-85a9-75db48d3501e.png)

![image](https://user-images.githubusercontent.com/44828242/49124844-df7b2180-f2f8-11e8-9a45-e6f637279724.png)

**Comment by longpizi** [comment]
下一版OK
