### ISSUE TITLE
商品页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#367]
![image](https://user-images.githubusercontent.com/44828242/49126367-43541900-f2fe-11e8-800a-5fd177348f43.png)
![image](https://user-images.githubusercontent.com/44828242/49126398-6088e780-f2fe-11e8-9e5a-a3b97a8b2908.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49722559-0560d880-fca0-11e8-9828-579701182093.png)
![wx20181210-172032](https://user-images.githubusercontent.com/41175757/49722567-07c33280-fca0-11e8-89e6-fd4f44957e3f.png)
商品页面，layout broken #367
