### ISSUE TITLE
商品页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#371]
![image](https://user-images.githubusercontent.com/44828242/49131197-3c370600-f312-11e8-899e-c4fae8f9b93e.png)
http://www.membersheep.cn/Goods/Index?goodsId=30

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49722796-799b7c00-fca0-11e8-87d2-ebf01b2c5fb9.png)
商品页面，layout broken #371
