### ISSUE TITLE
供货商，order management ->order history

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#376]
![image](https://user-images.githubusercontent.com/44828242/49132802-ad79b780-f318-11e8-9bce-9757675ced4b.png)

![image](https://user-images.githubusercontent.com/44828242/49132787-9d61d800-f318-11e8-82d9-28196a57288b.png)

**Comment by Jvisions** [comment]
这个是订单历史信息，要买过才行
