### ISSUE TITLE
左边显示的brand和商品显示不符合

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#381]
![image](https://user-images.githubusercontent.com/41175158/49134826-e10c1000-f31f-11e8-9e63-e0195357f8fd.png)

**Comment by Amber-Lily** [comment]
http://www.membersheep.cn/Category/Index?categoryId=50&parentsId=22

**Comment by longpizi** [comment]
下一版OK
