### ISSUE TITLE
出现一条横线

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#384]
![image](https://user-images.githubusercontent.com/41175158/49135588-1a457f80-f322-11e8-9287-ade30b30b70a.png)
http://www.membersheep.cn/Category/Index?categoryId=0&parentsId=2

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49138301-cb9be380-f329-11e8-954e-7b60952547b1.png)
ok
