### ISSUE TITLE
把滚动条，请去掉一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#385]
![image](https://user-images.githubusercontent.com/44828242/49135595-1ca7d980-f322-11e8-8d86-8b6b9b2e0146.png)
http://www.membersheep.cn/Store/Index?sellerId=44

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49138411-0ef65200-f32a-11e8-8d28-6ca21c0eb0f9.png)
ok
