### ISSUE TITLE
点击一个时没有错误，但是再点击取消就跳空白页

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#386]
![image](https://user-images.githubusercontent.com/41175158/49135653-51b42c00-f322-11e8-9943-ff11dcbc3994.png)

**Comment by Amber-Lily** [comment]
http://www.membersheep.cn/Category/Index?categoryId=0&parentsId=2

**Comment by longpizi** [comment]
下一版OK
