### ISSUE TITLE
商品添加到购物车，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#389]
![image](https://user-images.githubusercontent.com/44828242/49140033-33542d80-f32e-11e8-8635-969e254524c0.png)
![image](https://user-images.githubusercontent.com/44828242/49140129-6bf40700-f32e-11e8-8a51-2e6b9ea228ce.png)
![image](https://user-images.githubusercontent.com/44828242/49140141-77dfc900-f32e-11e8-993f-796c14f7bcf3.png)
![image](https://user-images.githubusercontent.com/44828242/49140252-c1c8af00-f32e-11e8-90be-71344e5fd6fb.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49140907-5ed81780-f330-11e8-9d9e-37fcb5937f02.png)
我测试是正确的啊

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49140972-8333f400-f330-11e8-87b6-d73eda9bcf52.png)
