### ISSUE TITLE
点击mycenter,跳转空白页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#390]
![image](https://user-images.githubusercontent.com/44828242/49140698-e40efc80-f32f-11e8-9d98-d05ef464b7bd.png)
![image](https://user-images.githubusercontent.com/44828242/49140737-01dc6180-f330-11e8-9684-9becaf22edd6.png)
![image](https://user-images.githubusercontent.com/44828242/49140748-09036f80-f330-11e8-882e-b27f324695e8.png)

**Comment by Jvisions** [comment]
你这是供货商账户肯定登不进采购商的个人中心的
