### ISSUE TITLE
供货商，发布品牌页面，出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#391]
![image](https://user-images.githubusercontent.com/44828242/49193720-1c0f5180-f3bb-11e8-96f8-2eeffdcbb678.png)
![image](https://user-images.githubusercontent.com/44828242/49193747-39442000-f3bb-11e8-857f-21373bf49c46.png)

**Comment by Jvisions** [comment]
这个改了，但是还没上传
