### ISSUE TITLE
购物车页面，数字需要居中

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#394]
![image](https://user-images.githubusercontent.com/44828242/49194688-1c115080-f3bf-11e8-8011-6504b2d7c270.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49725206-21677880-fca6-11e8-98aa-eb10ef6e4500.png)
购物车页面，数字需要居中 #394
