### ISSUE TITLE
商品详情页缺少一个向上返回键

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#397]
![image](https://user-images.githubusercontent.com/41175158/49196615-8f6a9080-f3c6-11e8-93b2-4099c8fe62e2.png)
http://www.membersheep.cn/Goods/Index?goodsId=7736

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49776945-49ec8280-fd39-11e8-8df8-b24c52161364.png)
![2](https://user-images.githubusercontent.com/41175757/49776947-4b1daf80-fd39-11e8-82ac-ce164ee3f50b.png)
商品详情页缺少一个向上返回键 #397
