### ISSUE TITLE
清单里出货地，商品详情页是生产地，要统一一下

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#398]
![image](https://user-images.githubusercontent.com/41175158/49196682-c9d42d80-f3c6-11e8-8f23-4e63a5e3e676.png)
![image](https://user-images.githubusercontent.com/41175158/49196694-d5275900-f3c6-11e8-9215-f6e7c1f7417f.png)

**Comment by longpizi** [comment]
下一版OK
