### ISSUE TITLE
店铺名称，可下单日期

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#400]
![image](https://user-images.githubusercontent.com/44828242/49197031-487d9a80-f3c8-11e8-900d-0884bf77f1fe.png)
http://www.membersheep.cn/Store/Index?sellerId=120

**Comment by Jvisions** [comment]
没有店铺名，第一个是商品名，第二个是品牌名

**Comment by piaoseeun** [comment]
ok
