### ISSUE TITLE
显示商品名称，和实在商品名称不一样

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#401]
![image](https://user-images.githubusercontent.com/44828242/49197139-b9bd4d80-f3c8-11e8-966b-48b579181713.png)
![image](https://user-images.githubusercontent.com/44828242/49197270-3fd99400-f3c9-11e8-8c11-2169042fa329.png)
http://www.membersheep.cn/Store/Index?sellerId=120

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49201459-e9c21c00-f3db-11e8-8c04-741b425778bf.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49201470-f2b2ed80-f3db-11e8-860a-1d97bc9468d3.png)
这个一样的啊
