### ISSUE TITLE
店铺页面，出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#402]
![image](https://user-images.githubusercontent.com/44828242/49201265-3a854500-f3db-11e8-8133-77e99a12dbff.png)
http://www.membersheep.cn/Store/Index?sellerId=120

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49201871-a8cb0700-f3dd-11e8-9936-35aec2637be2.png)
我这里没问题啊
