### ISSUE TITLE
滚动条，请去掉一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#403]
![image](https://user-images.githubusercontent.com/44828242/49201380-a5cf1700-f3db-11e8-94ce-cc74d31216be.png)
http://www.membersheep.cn/Store/AuthorityList

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49780336-19144980-fd49-11e8-9b2a-5f3fdbbe574c.png)
滚动条，请去掉一下 #403
