### ISSUE TITLE
搜索框layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#404]
![image](https://user-images.githubusercontent.com/44828242/49202731-8a1a3f80-f3e0-11e8-82f8-8dde19a66e69.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49780629-54634800-fd4a-11e8-9ef6-33c57622a9ff.png)
搜索框layout broken #404
