### ISSUE TITLE
位置错乱

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#412]
![image](https://user-images.githubusercontent.com/41175158/49212510-1c304100-f3fd-11e8-9f70-fe4c9f23be11.png)
http://www.membersheep.cn/Store/Index?sellerId=48

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49780673-87a5d700-fd4a-11e8-86b4-d7313c94f7b6.png)
位置错乱 #412
