### ISSUE TITLE
店铺页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#413]
![image](https://user-images.githubusercontent.com/44828242/49212762-c60fcd80-f3fd-11e8-8204-c91036994594.png)
http://www.membersheep.cn/Store/Index?sellerId=48

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49780690-97bdb680-fd4a-11e8-8855-90186a252945.png)
店铺页面，出现问题 #413
