### ISSUE TITLE
品牌下拉菜单，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#419]
![image](https://user-images.githubusercontent.com/44828242/49264519-8ee6fe00-f489-11e8-9dcf-9f6e007c9567.png)
![image](https://user-images.githubusercontent.com/44828242/49264542-ac1bcc80-f489-11e8-9477-353d4b1aa387.png)
www.membersheep.cn/Category/Index?categoryId=59&parentsId=23

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49780730-cb004580-fd4a-11e8-9dc8-fce5840997d3.png)
品牌下拉菜单，layout broken #419
