### ISSUE TITLE
调整按钮位置

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#421]
![image](https://user-images.githubusercontent.com/41175158/49264726-6dd2dd00-f48a-11e8-96b1-bcbf9f8fd48f.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49781369-65618880-fd4d-11e8-8539-795b1bd47e61.png)
调整按钮位置 #421
