### ISSUE TITLE
选择性别，年龄->商品不见了

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#425]
![image](https://user-images.githubusercontent.com/44828242/49265086-c060c900-f48b-11e8-815e-4259052f0a15.png)
![image](https://user-images.githubusercontent.com/44828242/49265043-a1facd80-f48b-11e8-852e-1485373a5ed3.png)
http://www.membersheep.cn/Category/Index?categoryId=58&parentsId=23

**Comment by Jvisions** [comment]
这个肯定没有呢，这是要满足所有年龄段的商品，怎么会有
