### ISSUE TITLE
购物车，显示数字

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#431]
![image](https://user-images.githubusercontent.com/44828242/49265544-81337780-f48d-11e8-8665-6c1b37bdb717.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49265618-d40d2f00-f48d-11e8-91c6-0458641b7766.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49265630-e5563b80-f48d-11e8-8666-90d326b06448.png)
没问题呢？
