### ISSUE TITLE
商品页面，是否可以加一个按钮吗？

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#434]
![image](https://user-images.githubusercontent.com/44828242/49269253-fd828680-f49e-11e8-92f4-ea6992b3ef83.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49781440-a6f23380-fd4d-11e8-8f5c-8b3992e4ee8f.png)
再点击弹出窗口管理
