### ISSUE TITLE
缺少了边框

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#436]
![image](https://user-images.githubusercontent.com/41175158/49270289-91eee800-f4a3-11e8-959a-923dba080818.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by ErisFU** [comment]
![5](https://user-images.githubusercontent.com/41175757/49337159-c13f5980-f649-11e8-9cc3-a24d4e759a03.png)
 你浏览器缓存清理下，之前改好了
