### ISSUE TITLE
性别选择，商品没有变化

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#441]
![image](https://user-images.githubusercontent.com/41175158/49271356-32470b80-f4a8-11e8-9232-e583d839850d.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=222

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49271397-6ae6e500-f4a8-11e8-92a2-1053fab2a6a3.png)
选择这些也没反应

**Comment by longpizi** [comment]
下一版OK
