### ISSUE TITLE
商品只有一页，往下翻页还可以继续点

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#443]
![image](https://user-images.githubusercontent.com/41175158/49271532-15f79e80-f4a9-11e8-8c34-23b2a1e8510c.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=155

**Comment by Amber-Lily** [comment]
发现把价格从高到低或者低到高选择上就会出现这样的情况

**Comment by longpizi** [comment]
下一版OK
