### ISSUE TITLE
我建议“brands” 加一个链接

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#444]
![image](https://user-images.githubusercontent.com/44828242/49271758-fad95e80-f4a9-11e8-8821-be9bd8207206.png)
![image](https://user-images.githubusercontent.com/44828242/49271791-18a6c380-f4aa-11e8-9518-c2fe3f917b25.png)

**Comment by Jvisions** [comment]
没必要，他就是一个说明的作用，而且要这样改的话所有页面都要改
