### ISSUE TITLE
推荐商品页面符号垂直居中

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#447]
![image](https://user-images.githubusercontent.com/29912212/49273816-290e6c80-f4b1-11e8-91ee-820ee0666cd3.png)

**Comment by ErisFU** [comment]
![4](https://user-images.githubusercontent.com/41175757/49337142-7f161800-f649-11e8-9e2b-e978c57fcb0c.png)
done OK
