### ISSUE TITLE
商品详情页产品图片垂直居中

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#455]
![image](https://user-images.githubusercontent.com/29912212/49277236-f28a1f00-f4bb-11e8-87e0-99bf1bd400b2.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49336705-4757a200-f642-11e8-9e1d-e4610e7d19db.png)
OK done
