### ISSUE TITLE
旁边有两个品牌，但是商品显示只有一种

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#457]
![image](https://user-images.githubusercontent.com/41175158/49278536-151e3700-f4c0-11e8-9ffa-0369cd05bb66.png)
http://www.membersheep.cn/Store/Index?sellerId=48

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49278627-4e56a700-f4c0-11e8-87ac-942f66a1b850.png)
商品品牌与旁边的不一致

**Comment by Amber-Lily** [comment]
其他分类也点点，都有这种情况

**Comment by longpizi** [comment]
下一版OK
