### ISSUE TITLE
这个收藏应该添加一个可以取消的，现在只能收藏不能取消

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#459]
![image](https://user-images.githubusercontent.com/41175158/49279578-db026480-f4c2-11e8-91d0-99701697aceb.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49781857-30eecc00-fd4f-11e8-82db-71e842d4e764.png)
点击去管理收藏
