### ISSUE TITLE
采购商支付预付款英文页面有韩文

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#46]
![image](https://user-images.githubusercontent.com/29912212/48311699-beb78a00-e5de-11e8-837e-f2f1f1948070.png)

**Comment by yellmi1983** [comment]
![image](https://user-images.githubusercontent.com/29912212/48311715-0c33f700-e5df-11e8-963d-e9a77c28ca38.png)

**Comment by yellmi1983** [comment]
![image](https://user-images.githubusercontent.com/29912212/48311722-3be2ff00-e5df-11e8-871f-1d5b24fcb89f.png)

**Comment by yellmi1983** [comment]
![image](https://user-images.githubusercontent.com/29912212/48311739-70ef5180-e5df-11e8-9793-870b3c6a9519.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48323633-0cc4a000-e668-11e8-91c1-7cd9283d71b6.png)
