### ISSUE TITLE
购物车缺少删除键

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#460]
![image](https://user-images.githubusercontent.com/41175158/49281034-84972500-f4c6-11e8-9614-deb69743fa0e.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49781898-5aa7f300-fd4f-11e8-834f-2d8f8a5df6a5.png)
购物车缺少删除键 #460
