### ISSUE TITLE
STYLEYINZ店铺页面，商品数量不对

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#463]
![image](https://user-images.githubusercontent.com/44828242/49348656-96a0df80-f6e1-11e8-911a-99c616197e19.png)
http://www.membersheep.cn/Store/Index?sellerId=32

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49495834-4f604d80-f89f-11e8-809a-d9bba49bcd7c.png)
我测得没问题啊
