### ISSUE TITLE
方框里的鼠标点进去之后文字可以消失

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#468]
![image](https://user-images.githubusercontent.com/41175158/49350952-28154f00-f6ec-11e8-8d96-7e7847b426ff.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49782508-904ddb80-fd51-11e8-9c79-423e99ecd32b.png)
输数字
