### ISSUE TITLE
输入两个三个数字就显示不全

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#470]
![image](https://user-images.githubusercontent.com/41175158/49351384-35cbd400-f6ee-11e8-86d4-43696172cd3f.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49784098-220c1780-fd57-11e8-8654-0279fa4c8e00.png)
输入两个三个数字就显示不全 #470
