### ISSUE TITLE
括号的错位了

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#471]
![image](https://user-images.githubusercontent.com/41175158/49351618-43358e00-f6ef-11e8-8968-9c190ca870d9.png)
http://www.membersheep.cn/Goods/Index?goodsId=2319

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49422121-8403d480-f7cd-11e8-84f9-e6d73ad81ff7.png)
OK
