### ISSUE TITLE
商品页面，order now 和add to cart 按钮位置调整一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#478]
![image](https://user-images.githubusercontent.com/44828242/49360093-2317c600-f713-11e8-9aea-32544213e34c.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49506066-197b9300-f8b8-11e8-94d8-f7522145a8e9.png)
OK商品页面，order now 和add to cart 按钮位置调整一下 #478
