### ISSUE TITLE
Best seller 页面，链接错误问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#479]
![image](https://user-images.githubusercontent.com/44828242/49360790-23b15c00-f715-11e8-8bcd-259bacc1a54d.png)
![image](https://user-images.githubusercontent.com/44828242/49360891-79860400-f715-11e8-9802-3b3d399b749b.png)

**Comment by Jvisions** [comment]
这就是商品啊，点击跳转购买页面
