### ISSUE TITLE
搜索品牌，无结果

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#489]
![image](https://user-images.githubusercontent.com/44828242/49413891-53f80980-f7ac-11e8-9f6f-742e888e841c.png)

![image](https://user-images.githubusercontent.com/44828242/49413824-214e1100-f7ac-11e8-95f7-c235ffe17e84.png)
![image](https://user-images.githubusercontent.com/44828242/49413830-2612c500-f7ac-11e8-9984-713325d3d477.png)
![image](https://user-images.githubusercontent.com/44828242/49413841-2b700f80-f7ac-11e8-89e9-7d32b8fd1ea6.png)

**Comment by Jvisions** [comment]
这如果是没有这个品牌的话肯定就是0 啊
