### ISSUE TITLE
页码栏做成一排的

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#491]
![image](https://user-images.githubusercontent.com/41175158/49414403-3f1c7580-f7ae-11e8-87d3-f5e8b1ff59d8.png)
![image](https://user-images.githubusercontent.com/41175158/49414437-5ce9da80-f7ae-11e8-9219-dab9678b4ec2.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=144

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49505768-69a62580-f8b7-11e8-9ab5-68da300ae57b.png)
OK页码栏做成一排的 #491
