### ISSUE TITLE
PRADA 品牌页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#492]
![image](https://user-images.githubusercontent.com/44828242/49417484-e0102e00-f7b8-11e8-8045-2011b986bfb6.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=219

**Comment by Jvisions** [comment]
要登录，英文意思就一个啊，永久有效

**Comment by piaoseeun** [comment]
![image](https://user-images.githubusercontent.com/44828242/49423685-38ecc000-f7d3-11e8-8d2d-fddcd33388fa.png)
金成，我这个页面登入进去的，再看一下

**Comment by Jvisions** [comment]
经理那边还没上传，等传好了就行了

**Comment by piaoseeun** [comment]
OK
