### ISSUE TITLE
两个页面的页码栏不一样

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#495]
![image](https://user-images.githubusercontent.com/41175158/49425101-97b43880-f7d7-11e8-98ab-f04ed58a368c.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=222
![image](https://user-images.githubusercontent.com/41175158/49425108-a00c7380-f7d7-11e8-9833-30dd60c33d6f.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=155

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49505696-4aa79380-f8b7-11e8-8233-cd8ffe3b3d4b.png)
ok两个页面的页码栏不一样 #495
