### ISSUE TITLE
购物车

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#498]
![image](https://user-images.githubusercontent.com/41175158/49430812-f9c86a00-f7e6-11e8-8161-dc152fd9753a.png)
http://www.membersheep.cn/Home/OrandRequest

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49430890-25e3eb00-f7e7-11e8-9ee5-b103e3697f37.png)
http://www.membersheep.cn/Home/NewGoods
缺少东西

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49431040-7bb89300-f7e7-11e8-93d4-1c7928096b6f.png)
首页

**Comment by Amber-Lily** [comment]
有购物车的页面，打开自动显示购物车

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49431110-ac98c800-f7e7-11e8-8bc0-6a7569583ba2.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49785347-423dd580-fd5b-11e8-9a69-91d0524b46f0.png)
购物车 #498
