### ISSUE TITLE
手机版，首页有缝隙

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#499]
![image](https://user-images.githubusercontent.com/41175158/49431480-917a8800-f7e8-11e8-833a-fbdc8e78cabc.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49431576-d0104280-f7e8-11e8-9aab-e7c3136b1535.png)
这个是不是应该在一排

**Comment by Amber-Lily** [comment]
首页缺少语言切换的功能

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433694-8b3ada80-f7ed-11e8-8445-abeba3238752.png)
布局出错

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433740-a4dc2200-f7ed-11e8-9e9e-9b58a9a2c4eb.png)
点了链接后，字变色

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433907-00a6ab00-f7ee-11e8-801a-df2670cfc803.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433960-1c11b600-f7ee-11e8-8462-a274f94b27ee.png)
字超出了

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49434065-55e2bc80-f7ee-11e8-97bc-7adb5edc7b7f.png)
搜索功能不能用

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49434182-93dfe080-f7ee-11e8-903a-c162609e8d57.png)
链接链到鞋子页面了，应该是首饰页面

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49788704-01e35500-fd65-11e8-8b45-7f631721624d.png)
![2](https://user-images.githubusercontent.com/41175757/49788707-04de4580-fd65-11e8-9b7c-be9971c72fc1.png)
![3](https://user-images.githubusercontent.com/41175757/49788713-07d93600-fd65-11e8-89b6-94d2dc696173.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49849935-a1145500-fe16-11e8-9462-18a81aac95bf.png)
语言切换 OK
