### ISSUE TITLE
手机版，http://www.membersheep.cn/Home/NewGoods

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#500]
![image](https://user-images.githubusercontent.com/41175158/49432045-c20ef180-f7e9-11e8-9269-98ad92a5c4ed.png)
有缝隙

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49432462-b839be00-f7ea-11e8-90dd-7fcf173a01e3.png)
出现中文

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433311-ace79200-f7ec-11e8-89fe-3ac4fe0898f7.png)
链接到首页去了

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49433419-f2a45a80-f7ec-11e8-947f-3b40dca83bb4.png)
搜索功能不能用

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/49434313-df928a00-f7ee-11e8-9f69-6503bb9fe0b7.png)
点击之后字变颜色

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49850994-9e1b6380-fe1a-11e8-931a-d8136f3a1988.png)

**Comment by ErisFU** [comment]
手机版，http://www.membersheep.cn/Home/NewGoods #500
