### ISSUE TITLE
商品重复问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#506]
![image](https://user-images.githubusercontent.com/44828242/49487971-b40bb000-f87f-11e8-88b2-fcdb6c02d153.png)
http://www.membersheep.cn/Store/Index?sellerId=22
![image](https://user-images.githubusercontent.com/44828242/49488066-195fa100-f880-11e8-8924-bc8a571f5639.png)
http://www.membersheep.cn/Store/Index?sellerId=21
![image](https://user-images.githubusercontent.com/44828242/49488096-3e541400-f880-11e8-888a-1043c385fdab.png)
http://www.membersheep.cn/Store/Index?sellerId=21

**Comment by longpizi** [comment]
下一版OK
