### ISSUE TITLE
商品分类出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#513]
![image](https://user-images.githubusercontent.com/44828242/49494476-c2b39080-f89a-11e8-812d-3793e1cdc885.png)
![image](https://user-images.githubusercontent.com/44828242/49494677-656c0f00-f89b-11e8-95ae-5ba756c266db.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49495400-d0b6e080-f89d-11e8-85ac-e03687bac365.png)
我测试没问题
