### ISSUE TITLE
商品详情页下面不一样

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#515]
![image](https://user-images.githubusercontent.com/41175158/49500819-82f5a480-f8ac-11e8-9f14-ae04bb3915f2.png)
![image](https://user-images.githubusercontent.com/41175158/49500830-8ab54900-f8ac-11e8-9818-5e120c5fd030.png)

**Comment by Jvisions** [comment]
详细信息是一个空格
