### ISSUE TITLE
购物车页面的购物车和其他页面的不一样

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#516]
![Uploading image.png…]()
http://www.membersheep.cn/Cart/Index

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49851984-cb1d4580-fe1d-11e8-983a-c2f539d0fd17.png)
![2](https://user-images.githubusercontent.com/41175757/49851988-cce70900-fe1d-11e8-881a-86d419a96506.png)
一样啊
