### ISSUE TITLE
TOMMY HILFIGER，商品信息没显示

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#522]
![image](https://user-images.githubusercontent.com/44828242/49555859-630dc180-f93c-11e8-9275-ef025580c843.png)
![image](https://user-images.githubusercontent.com/44828242/49555885-80429000-f93c-11e8-825c-3dd093ac688e.png)
http://www.membersheep.cn/Category/Index?categoryId=67&parentsId=2

**Comment by Amber-Lily** [comment]
这个有问题，等龙林改好了我再修改
