### ISSUE TITLE
购物车页面，Deletea按钮出现不一定

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#530]
![image](https://user-images.githubusercontent.com/44828242/49560754-a3763b00-f94e-11e8-9147-89282cf9ddf5.png)
![image](https://user-images.githubusercontent.com/44828242/49563770-2225a500-f95c-11e8-8b0a-cc496c05e4b1.png)

**Comment by Jvisions** [comment]
我测试没问题
