### ISSUE TITLE
这个牌子的表不能修改尺寸

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#531]
![image](https://user-images.githubusercontent.com/41175158/49565189-4df75980-f961-11e8-8fa2-947f75e27cc1.png)
![image](https://user-images.githubusercontent.com/41175158/49565278-9dd62080-f961-11e8-84c8-286e1df94d04.png)
http://www.membersheep.cn/AdminSeller/GoodsList

**Comment by Amber-Lily** [comment]
tommy的也不能修改

**Comment by longpizi** [comment]
下一版OK
