### ISSUE TITLE
组织分类，有不正确的，需要修改

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#534]
![image](https://user-images.githubusercontent.com/44828242/49568462-03c7a580-f96c-11e8-8c00-ca394f42dbc9.png)
![image](https://user-images.githubusercontent.com/44828242/49568473-088c5980-f96c-11e8-9bbc-f7124d463630.png)
http://www.membersheep.cn/Category/Index?categoryId=122&parentsId=97
http://www.membersheep.cn/Goods/Index?goodsId=2345

**Comment by Amber-Lily** [comment]
这个好像是分类的问题，就是可能要他们看看 能不能改，你可以给金成看看

**Comment by piaoseeun** [comment]
嗯嗯，金成帮我看下
