### ISSUE TITLE
首页出现问题，没有链接

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#535]
![image](https://user-images.githubusercontent.com/44828242/49570592-0af1b200-f972-11e8-8c8a-78d3c36a3d49.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49571197-8f910000-f973-11e8-843d-4eb7b7aa7135.png)
我测试没有问题
