### ISSUE TITLE
中文界面，语言选择功能布局错乱

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#541]
![image](https://user-images.githubusercontent.com/41175158/49573561-3deb7400-f979-11e8-9ea3-1fbed2c50b3d.png)
http://www.membersheep.cn/MyPage/MyAddress?addressId=23

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49859517-ac757980-fe32-11e8-9141-0cd0e14332fe.png)
中文界面，语言选择功能布局错乱 #541
