### ISSUE TITLE
购物车layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#542]
![image](https://user-images.githubusercontent.com/44828242/49574791-2366ca00-f97c-11e8-9432-03908aec18b2.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49859580-d5960a00-fe32-11e8-982c-53086b2e8deb.png)
购物车layout broken #542
