### ISSUE TITLE
购物车样式不同

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#543]
![image](https://user-images.githubusercontent.com/41175158/49575482-bce2ab80-f97d-11e8-9fb7-8324b72bb3dd.png)
![image](https://user-images.githubusercontent.com/41175158/49575500-c835d700-f97d-11e8-8a6d-e810a7504b5e.png)

**Comment by ErisFU** [comment]
两个头 新头好老头部 是不一样的
