### ISSUE TITLE
采购商信息栏文字错位

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#55]
![image](https://user-images.githubusercontent.com/29912212/48324268-0d126a80-e66b-11e8-9d06-99319563b73c.png)

**Comment by ErisFU** [comment]
![wx20181112-141229](https://user-images.githubusercontent.com/41175757/48329774-32ac6d80-e685-11e8-8035-4c8167219bf7.png)
okOK done
