### ISSUE TITLE
空白页

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#552]
![image](https://user-images.githubusercontent.com/41175158/49623700-a4b86e00-fa09-11e8-8c1e-1ba1393c489f.png)
http://www.membersheep.cn/Goods/Index?goodsId=327

**Comment by longpizi** [comment]
![image](https://user-images.githubusercontent.com/37363309/49987117-27fb3600-ffad-11e8-9661-400d454fed38.png)
