### ISSUE TITLE
菜单数与显示的数量不正确

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#561]
![image](https://user-images.githubusercontent.com/44828242/49629388-48af1300-fa24-11e8-912c-eb74c1f12528.png)
![image](https://user-images.githubusercontent.com/44828242/49629415-5cf31000-fa24-11e8-9af8-c8f0ef328a30.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=214

**Comment by Jvisions** [comment]
七页数据，每页八条数据
