### ISSUE TITLE
商品名称修改好后，被自动改回

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#569]
![image](https://user-images.githubusercontent.com/44828242/49630871-e3125500-fa2a-11e8-9e5a-507373ab1433.png)
http://www.membersheep.cn/Store/Index?sellerId=48

商品名称不对->佳佳修改好->被自动改回

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49725076-d6e5fc00-fca5-11e8-8b1e-4ff14d5fed76.png)
我可以修改啊？你要修改成什么？我来帮你改

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49725106-ec5b2600-fca5-11e8-851c-9c9dfaf2c56d.png)
数据库随便改
