### ISSUE TITLE
显示商品名称与实际商品名称不符合

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#572]
![image](https://user-images.githubusercontent.com/44828242/49631208-16a1af00-fa2c-11e8-87cc-d02eb9e2ab27.png)
![image](https://user-images.githubusercontent.com/44828242/49631221-23260780-fa2c-11e8-8355-fa96ce690e8f.png)
![image](https://user-images.githubusercontent.com/44828242/49631241-31742380-fa2c-11e8-9e7d-7916e911ed98.png)
现在很多商品有这样问题，帮帮我查一下

**Comment by Jvisions** [comment]
这个不是系统的问题，是数据库数据的问题
