### ISSUE TITLE
购物车total金额出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#573]
![image](https://user-images.githubusercontent.com/44828242/49632849-27edba00-fa32-11e8-9405-a7f981e10e37.png)

**Comment by Jvisions** [comment]
你可能页面没有刷新，我测试的没有问题
![image](https://user-images.githubusercontent.com/39116593/49633080-fde8c780-fa32-11e8-9846-faa7a9329633.png)
