### ISSUE TITLE
商品重复问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#575]
![image](https://user-images.githubusercontent.com/44828242/49634397-89645780-fa37-11e8-85a1-64849a9bd0b0.png)
![image](https://user-images.githubusercontent.com/44828242/49634404-908b6580-fa37-11e8-83cb-fa4fcf3fd517.png)
![image](https://user-images.githubusercontent.com/44828242/49634418-97b27380-fa37-11e8-80dd-ce51cbd4c49c.png)
http://www.membersheep.cn/Store/Index?sellerId=112

**Comment by Amber-Lily** [comment]
交给龙林了，这两个商品ID 是一样的

**Comment by piaoseeun** [comment]
OK
