### ISSUE TITLE
Modify Product页面，提示框layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#577]
![image](https://user-images.githubusercontent.com/44828242/49635547-1c52c100-fa3b-11e8-8fa4-df3cc0d3d8cf.png)
http://www.membersheep.cn/AdminSeller/GoodsModify?goodsId=7629

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49988542-149e9980-ffb2-11e8-98ae-9567ba476361.png)
Modify Product页面，提示框layout broken #577
