### ISSUE TITLE
除了首页和新品等那一排。其余的网页，鼠标移上去字会变黄和有下划线

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#578]
![image](https://user-images.githubusercontent.com/41175158/49635823-e19d5880-fa3b-11e8-9a41-2e29ddf69dc1.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49990981-91357600-ffba-11e8-8914-bbb16046117a.png)

除了首页和新品等那一排。其余的网页，鼠标移上去字会变黄和有下划线 #578
