### ISSUE TITLE
Sell->Product Management ->Registered, 品牌名称剧中

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#58]
![image](https://user-images.githubusercontent.com/44828242/48324487-e99bef80-e66b-11e8-9bfb-0516300300b6.png)

网址：http://www.membersheep.cn/AdminSeller/Brand

**Comment by ErisFU** [comment]
![wx20181112-121130](https://user-images.githubusercontent.com/41175757/48326409-44394980-e674-11e8-8b8e-ece3e2c9d0fb.png)
ok!done
