### ISSUE TITLE
除了首页和新品那一排的按钮的页面，其他的页面鼠标移上去不会变颜色

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#581]
![image](https://user-images.githubusercontent.com/41175158/49639244-78224780-fa45-11e8-88dd-87d511386358.png)

**Comment by Jvisions** [comment]
这个是改版还没改完全，只有三四个页面是用的新的头，其他的都是老的头部，改版完成之后就好了
