### ISSUE TITLE
商品栏少了一个框

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#582]
![image](https://user-images.githubusercontent.com/41175158/49706666-35898680-fc62-11e8-9c8b-426dc94f2276.png)
![image](https://user-images.githubusercontent.com/41175158/49706668-3b7f6780-fc62-11e8-9751-528d0d8b1a3a.png)

**Comment by Jvisions** [comment]
这个是少商品，你要上传

**Comment by Amber-Lily** [comment]
之前已经好了的
