### ISSUE TITLE
shpcoin比特币及以太币支付按钮错位(windows正常，mac错位)

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#59]
![image](https://user-images.githubusercontent.com/29912212/48324596-68912800-e66c-11e8-9632-677ee4caee19.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48326101-9ed1a600-e672-11e8-9524-a0ae90e0b8fc.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48328423-d21a3200-e67e-11e8-9dc8-49732abcc91b.png)
