### ISSUE TITLE
供货商sales management页面，出现问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#592]
![image](https://user-images.githubusercontent.com/44828242/49717763-03dce380-fc93-11e8-949b-d4efc719dced.png)
http://www.membersheep.cn/AdminSeller/SellingPrice

**Comment by ErisFU** [comment]
<img width="1261" alt="1" src="https://user-images.githubusercontent.com/41175757/50064976-07222300-01ef-11e9-843b-7abc8dbe8f0d.png">
供货商sales management页面，出现问题 #592
