### ISSUE TITLE
评论区上传图片还是缺少边框

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#597]
![image](https://user-images.githubusercontent.com/41175158/49720357-83ba7c00-fc9a-11e8-9147-c4082fe255b7.png)
http://www.membersheep.cn/MyPage/Order

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49852310-bc835e00-fe1e-11e8-80d8-d093a089013b.png)
我试过了，没有问题
