### ISSUE TITLE
购物车save不居中

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#598]
![image](https://user-images.githubusercontent.com/41175158/49720455-c11f0980-fc9a-11e8-8dca-6f8ddaa1cf06.png)
http://www.membersheep.cn/Goods/Index?goodsId=2371

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50071800-eddc9f00-020d-11e9-88a8-132b9b356223.png)
购物车save不居中 #598
