### ISSUE TITLE
close变成黑条了

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#599]
![image](https://user-images.githubusercontent.com/41175158/49720604-338fe980-fc9b-11e8-81c0-f354d47d03ef.png)
http://www.membersheep.cn/Goods/Index?goodsId=65

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50272050-86bf2480-0471-11e9-98b0-2ae12289addc.png)
![wx20181220-155045](https://user-images.githubusercontent.com/41175757/50272052-87f05180-0471-11e9-871a-fe472b5d3ea4.png)
![2](https://user-images.githubusercontent.com/41175757/50272058-89ba1500-0471-11e9-8394-0b2fc30b2226.png)
close变成黑条了 #599
