### ISSUE TITLE
商品详情页

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#60]
![image](https://user-images.githubusercontent.com/41175158/48324677-e1907f80-e66c-11e8-886e-ec7f866ceed9.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48325058-ca529180-e66e-11e8-94cf-a7592836cf40.png)
![image](https://user-images.githubusercontent.com/41175158/48325095-f4a44f00-e66e-11e8-83fe-e2b10cb8b766.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48333948-17952a00-e694-11e8-84d3-2ba4d5a5ec08.png)

**Comment by Jvisions** [comment]
尺码标准是用户自己写的，改不了英文

**Comment by Jvisions** [comment]
经过和蕊的深刻探讨，上下两个表格没有任何关系，没必要
