### ISSUE TITLE
页码应在一排

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#601]
![image](https://user-images.githubusercontent.com/41175158/49720960-14458c00-fc9c-11e8-9cd6-ccce91931f6d.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=214

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/49851888-72e64380-fe1d-11e8-91ac-b2a56d48e006.png)
没有问题
