### ISSUE TITLE
order request页面，layout broken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#605]
![image](https://user-images.githubusercontent.com/44828242/49724967-9a1a0500-fca5-11e8-99f4-e2b8a420054a.png)

**Comment by ErisFU** [comment]
<img width="1217" alt="1" src="https://user-images.githubusercontent.com/41175757/50212045-063aee00-03b5-11e9-8814-1d6ea7af14c5.png">
order request页面，layout broken #605
