### ISSUE TITLE
订单历史按钮暂时隐藏

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#61]
![image](https://user-images.githubusercontent.com/29912212/48328136-a5194f80-e67d-11e8-9440-5f7802bcc330.png)

**Comment by Amber-Lily** [comment]
![image](https://user-images.githubusercontent.com/41175158/48337750-cdfe0c80-e69e-11e8-981e-7e1bca1e6643.png)
