### ISSUE TITLE
这个似乎掉下来了

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#614]
![image](https://user-images.githubusercontent.com/41175158/49776153-d8f79b80-fd35-11e8-8c7a-34ad1f0056bc.png)
http://www.membersheep.cn/MyPage/Order

**Comment by ErisFU** [comment]
<img width="535" alt="1" src="https://user-images.githubusercontent.com/41175757/50212428-08ea1300-03b6-11e9-925b-6719848a99fd.png">
这个似乎掉下来了 #614
