### ISSUE TITLE
layout broken (供货商order detail)

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#615]
![image](https://user-images.githubusercontent.com/44828242/49776300-6935e080-fd36-11e8-8206-ff3b2800c1cb.png)
http://www.membersheep.cn/AdminSeller/Order
blues1988@naver.com

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50212943-384d4f80-03b7-11e9-836f-471c39983221.png)
layout broken (供货商order detail) #615
