### ISSUE TITLE
供货商Sales Management页面，layoutbroken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#616]
![image](https://user-images.githubusercontent.com/44828242/49776869-e95d4580-fd38-11e8-8043-058023862f04.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50267292-ba924e00-0461-11e9-9c71-d7b941246062.png)
供货商Sales Management页面，layoutbroken #616
