### ISSUE TITLE
供货商登入，order detail 页面，请居中

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#619]
![image](https://user-images.githubusercontent.com/44828242/49777483-aea8dc80-fd3b-11e8-8004-1f333f1ecb76.png)

**Comment by ErisFU** [comment]
<img width="969" alt="1" src="https://user-images.githubusercontent.com/41175757/50260058-b9512900-0441-11e9-9b40-a070d49d236a.png">
供货商登入，order detail 页面，请居中 #619
