### ISSUE TITLE
供货商 order management 页面，layout broken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#620]
![image](https://user-images.githubusercontent.com/44828242/49780866-6abdd380-fd4b-11e8-93c6-4e149cd37909.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50262608-19010180-044d-11e9-91fa-1d2c4c21fbfc.png)
供货商 order management 页面，layout broken #620
 Open
