### ISSUE TITLE
1. ADIDAS 鞋子设定价格好奇怪，2. layout broken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#623]
![image](https://user-images.githubusercontent.com/44828242/49783804-094f3200-fd56-11e8-8fe6-cff07024f0e2.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50262709-94fb4980-044d-11e9-82b2-db8c329f671d.png)
1. ADIDAS 鞋子设定价格好奇怪，2. layout broken #623
