### ISSUE TITLE
save按钮向上走了

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#624]
![image](https://user-images.githubusercontent.com/41175158/49784054-f9841d80-fd56-11e8-85b6-f139e9d1bef5.png)
http://www.membersheep.cn/Home/NewGoods

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50262856-25d22500-044e-11e9-8303-63da7e7905f2.png)
save按钮向上走了 #624
