### ISSUE TITLE
品牌THE RUMI页面，出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#625]
![image](https://user-images.githubusercontent.com/44828242/49784483-6d72f580-fd58-11e8-9d1c-86f0d6f8575d.png)
http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=172

**Comment by Jvisions** [comment]
这个是数据库存的，玩家自己编译的，无法国际化

**Comment by piaoseeun** [comment]
嗯嗯那我交给佳佳
