### ISSUE TITLE
无法修改商品图片，没有信息

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#629]
![image](https://user-images.githubusercontent.com/44828242/49785542-e45dbd80-fd5b-11e8-840c-3465a8669af0.png)
![image](https://user-images.githubusercontent.com/44828242/49785573-03f4e600-fd5c-11e8-98c4-64a0dd531581.png)
供货商：blues1988@naver.com

**Comment by longpizi** [comment]
![image](https://user-images.githubusercontent.com/37363309/49982259-a4cee580-ff96-11e8-9417-5574ff5f1160.png)
可以了
