### ISSUE TITLE
1. 商品重复问题 2. 图片太模糊

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#630]
![image](https://user-images.githubusercontent.com/44828242/49787841-b16af800-fd62-11e8-9019-11920e525901.png)
http://www.membersheep.cn/Brand/DetailSearch?brandId=77

**Comment by Amber-Lily** [comment]
不是重复，因为有几个颜色，但是包包现在只有一个
