### ISSUE TITLE
供货商登入，order management ->details 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#633]
![image](https://user-images.githubusercontent.com/44828242/49910583-328ad200-febe-11e8-9bc2-4551cad3d30e.png)

![image](https://user-images.githubusercontent.com/44828242/49910564-1dae3e80-febe-11e8-9997-e9698e8dfd8f.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50268824-3347d900-0467-11e9-80c1-9aa2603f034e.png)
![wx20181220-145530](https://user-images.githubusercontent.com/41175757/50268863-507ca780-0467-11e9-8c04-a022a7810255.png)他们是不同的表格，先这样字吧
