### ISSUE TITLE
商品页面，我建议添加颜色名称

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#634]
![image](https://user-images.githubusercontent.com/44828242/49912625-b1cfd400-fec5-11e8-9dae-0763bd716d6a.png)
![image](https://user-images.githubusercontent.com/44828242/49912642-c3b17700-fec5-11e8-9bb0-320b176fd989.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50273598-0ea72d80-0476-11e9-9dea-1b63ae3c3432.png)
![wx20181220-155045](https://user-images.githubusercontent.com/41175757/50275945-a78c7780-047b-11e9-91fa-b0c96dad3e1b.png)
![1](https://user-images.githubusercontent.com/41175757/50275948-a9563b00-047b-11e9-946a-6024b88431dc.png)
![2](https://user-images.githubusercontent.com/41175757/50275952-ac512b80-047b-11e9-9fb2-074c8dfe1448.png)
商品页面，我建议添加颜色名称 #634
