### ISSUE TITLE
显示商品问题

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#635]
![image](https://user-images.githubusercontent.com/44828242/49912796-4c301780-fec6-11e8-9aac-1709cb826cba.png)
![image](https://user-images.githubusercontent.com/44828242/49912851-6ff35d80-fec6-11e8-9211-a0e7604a6182.png)
http://www.membersheep.cn/Store/Index?sellerId=112
供货商：blues1988@naver.com

**Comment by longpizi** [comment]
下一版OK
