### ISSUE TITLE
图片没见了，出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#64]
![image](https://user-images.githubusercontent.com/44828242/48336074-71005780-e69a-11e8-8646-bb7c652108f7.png)
![image](https://user-images.githubusercontent.com/44828242/48336144-955c3400-e69a-11e8-9b69-7fe9ed4f2492.png)

网址：http://www.membersheep.cn/GoodsList/QueryGoodsList?goodsListId=1

**Comment by Jvisions** [comment]
工厂交货是在数据库读出来的，暂时无法做到国际化

**Comment by Jvisions** [comment]
图片让佳佳传
