### ISSUE TITLE
商品尺寸助手按钮大小调整一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#640]
![image](https://user-images.githubusercontent.com/44828242/49918436-23b41780-fede-11e8-8da0-22531c1fad21.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50272021-7018cd80-0471-11e9-976a-19537a6609d1.png)
商品尺寸助手按钮大小调整一下 #640
