### ISSUE TITLE
商品尺寸表，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#641]
![image](https://user-images.githubusercontent.com/44828242/49918640-dbe1c000-fede-11e8-9122-d9f9750bb9e4.png)
http://www.membersheep.cn/Goods/Index?goodsId=6789

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50271874-11535400-0471-11e9-8a4e-162047a690ad.png)
![wx20181220-155045](https://user-images.githubusercontent.com/41175757/50271878-13b5ae00-0471-11e9-97fa-b3aa0198ba44.png)
![2](https://user-images.githubusercontent.com/41175757/50271886-16180800-0471-11e9-8e08-31631cd654ef.png)
商品尺寸表，layout broken #641
