### ISSUE TITLE
采购商mycenter 页面，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#643]
![image](https://user-images.githubusercontent.com/44828242/49922626-39303e00-feec-11e8-995e-f813bda74b4c.png)

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/50209951-f4a31780-03af-11e9-97be-c965cb540e42.png)
我这边测试是ok的
