### ISSUE TITLE
点击上移到最上面按钮位置好奇怪

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#644]
![image](https://user-images.githubusercontent.com/44828242/49923057-531e5080-feed-11e8-9728-9c36c5063075.png)
http://www.membersheep.cn/Goods/Index?goodsId=4887#gototop

**Comment by Jvisions** [comment]
![image](https://user-images.githubusercontent.com/39116593/50051472-ed7ccf00-014d-11e9-9913-1f9dcec172ca.png)
我这边测试还行啊，没什么问题
