### ISSUE TITLE
尺寸帮助layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#645]
![image](https://user-images.githubusercontent.com/44828242/49924803-1c970480-fef2-11e8-9eb9-7ed743379f29.png)
http://www.membersheep.cn/Goods/Index?goodsId=71

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50271949-3d6ed500-0471-11e9-9228-5cfdf8a1b76e.png)
![wx20181220-155045](https://user-images.githubusercontent.com/41175757/50271953-3f389880-0471-11e9-8cd8-bdc34bca501c.png)
![2](https://user-images.githubusercontent.com/41175757/50271956-419af280-0471-11e9-82fc-8c9974e8a799.png)
尺寸帮助layout broken #645
