### ISSUE TITLE
发布尺寸的地方和下载的表顺序不一样

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#652]
![image](https://user-images.githubusercontent.com/41175158/50067310-6423d600-01fb-11e9-8f40-92616a97e3b9.png)
![image](https://user-images.githubusercontent.com/41175158/50067403-d5fc1f80-01fb-11e9-93ee-9afbbfe0a54c.png)

**Comment by longpizi** [comment]
![image](https://user-images.githubusercontent.com/37363309/50194822-73c82980-0377-11e9-87ed-8892b2940cf5.png)
