### ISSUE TITLE
搜索框，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#654]
![image](https://user-images.githubusercontent.com/44828242/50273974-069bbd80-0477-11e9-81ae-361be8307281.png)
http://www.membersheep.cn/Home/Search

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50437574-47874c80-0925-11e9-9d34-816cf0aa25f8.png)
搜索框，layout broken #654
