### ISSUE TITLE
供货商登入，上传商品页面，layoutbroken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#656]
![image](https://user-images.githubusercontent.com/44828242/50276937-2a163680-047e-11e9-84ee-b9448045a244.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50436554-80252700-0921-11e9-9976-2ee2ad2165a3.png)
![wx20181226-151740](https://user-images.githubusercontent.com/41175757/50436555-80252700-0921-11e9-99e4-c72db47c11c5.png)
供货商登入，上传商品页面，layoutbroken #656
