### ISSUE TITLE
首页服饰配件模块上方空行太大

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#69]
![image](https://user-images.githubusercontent.com/29912212/48386104-d51f2c00-e72b-11e8-9a77-25a19a5929c0.png)

**Comment by ErisFU** [comment]
![wx20181114-180125](https://user-images.githubusercontent.com/41175757/48524594-e5661100-e8bb-11e8-97bc-bc7153b7bcbc.png)
OK done
