### ISSUE TITLE
品牌详情页

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/E-Commerce-dev#71]
![image](https://user-images.githubusercontent.com/41175158/48387216-d8b4b200-e72f-11e8-88c6-fdb08972f322.png)

**Comment by ErisFU** [comment]
![wx20181114-164816](https://user-images.githubusercontent.com/41175757/48470713-1cd9ac80-e82d-11e8-9ac3-1386f97a34f9.png)
OK done
