### ISSUE TITLE
搜索框图标layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#76]
![image](https://user-images.githubusercontent.com/44828242/48395142-3dcccf80-e751-11e8-9f0e-0bf4692420a4.png)

**Comment by ErisFU** [comment]
![wx20181114-145523](https://user-images.githubusercontent.com/41175757/48465297-59051100-e81d-11e8-8e52-6cba6b42b6e9.png)
done

**Comment by piaoseeun** [comment]
![image](https://user-images.githubusercontent.com/44828242/48524888-05e29b00-e8bd-11e8-9a2f-1e38303f9c9c.png)
