### ISSUE TITLE
按钮，字体

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#77]
![image](https://user-images.githubusercontent.com/44828242/48395163-50df9f80-e751-11e8-8687-280cccfa8b0a.png)

**Comment by ErisFU** [comment]
![wx20181114-145256](https://user-images.githubusercontent.com/41175757/48465201-04619600-e81d-11e8-96cc-e021b9dc854d.png)
ok  done
