### ISSUE TITLE
首页，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#84]
![image](https://user-images.githubusercontent.com/44828242/48525148-f44dc300-e8bd-11e8-8d9a-8c0f0520ecba.png)

**Comment by ErisFU** [comment]
![wx20181115-133243](https://user-images.githubusercontent.com/41175757/48533058-ed36ad00-e8dd-11e8-84bf-89dcbc2d079d.png)
OK done

**Comment by ErisFU** [comment]
![wx20181115-135356](https://user-images.githubusercontent.com/41175757/48533109-1d7e4b80-e8de-11e8-9480-936f398bb8df.png)
OK done
