### ISSUE TITLE
品牌页面layout broken , 出现中文

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#88]
![image](https://user-images.githubusercontent.com/44828242/48534556-6e447300-e8e3-11e8-9240-61cb968c0e65.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49556990-1aa4d280-f941-11e8-819c-d0a25985edb9.png)
中文不用去了，中文是logo的中文名 没关系的
