### ISSUE TITLE
order request ->显示空的页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#93]
![image](https://user-images.githubusercontent.com/44828242/48538870-8ff82700-e8f0-11e8-8043-a5edced962c7.png)
![image](https://user-images.githubusercontent.com/44828242/48538910-aaca9b80-e8f0-11e8-873a-fa6c09e1496d.png)
![image](https://user-images.githubusercontent.com/44828242/48538932-b918b780-e8f0-11e8-9c37-61318d904bde.png)

**Comment by Jvisions** [comment]
这个我测试没有问题啊
