### ISSUE TITLE
首页各模块没有商品或少商品的时候，页面错位了

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/E-Commerce-dev#94]
![image](https://user-images.githubusercontent.com/29912212/48540270-a43e2300-e8f4-11e8-8270-2148d432fbe2.png)

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49557204-dc5be300-f941-11e8-9e56-0ae9c8074a19.png)
第一个问题改好了，下面的交给小龙了
