### ISSUE TITLE
（中文界面）地址页面layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#97]
![image](https://user-images.githubusercontent.com/44828242/48592413-40167000-e983-11e8-93fc-3d6f111d549d.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49558604-99503e80-f946-11e8-97ed-2cdf32f41bc7.png)
![3-1](https://user-images.githubusercontent.com/41175757/49558606-9b1a0200-f946-11e8-882b-fa253faded6f.png)
OK done 因为地址比较长 所以要留的距离是不一样的
