### ISSUE TITLE
(中文界面）发布尺寸页面layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/E-Commerce-dev#99]
![image](https://user-images.githubusercontent.com/44828242/48592687-79031480-e984-11e8-836d-66275261bbef.png)

**Comment by ErisFU** [comment]
![4](https://user-images.githubusercontent.com/41175757/49558770-3ad79000-f947-11e8-8546-0c73a231bd5c.png)
OK (中文界面）发布尺寸页面layout broken #99
